//
// HealthMetricValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A representation of a health metric, either latest value or average value. */
public struct HealthMetricValue: Codable, JSONEncodable, Hashable {

    /** The value of the health metric. */
    public private(set) var amount: Double
    /** The kind of metric, either \"latestValue\" or \"average\". */
    public private(set) var kind: String
    /** The unit for the metric. */
    public private(set) var unit: String
    /** If the kind is \"average\", this is the period the average was conducted over, from today into the past. */
    public private(set) var periodDays: Int

    public init(amount: Double, kind: String, unit: String, periodDays: Int) {
        self.amount = amount
        self.kind = kind
        self.unit = unit
        self.periodDays = periodDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case kind
        case unit
        case periodDays = "period_days"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(kind, forKey: .kind)
        try container.encode(unit, forKey: .unit)
        try container.encode(periodDays, forKey: .periodDays)
    }
}

