//
// HealthMetricSample.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A sample of a health metric on a specific date. */
public struct HealthMetricSample: Codable, JSONEncodable, Hashable {

    /** An ISO-8601 formatted date. */
    public private(set) var date: Date?
    /** The quantity of the health metric */
    public private(set) var quantity: Double?
    /** The unit associated with the provided quantity. */
    public private(set) var unit: String?

    public init(date: Date? = nil, quantity: Double? = nil, unit: String? = nil) {
        self.date = date
        self.quantity = quantity
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case quantity
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(date, forKey: .date)
        try container.encodeIfPresent(quantity, forKey: .quantity)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

