//
// HealthWorkout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A representation of a workout the user performed. */
public struct HealthWorkout: Codable, JSONEncodable, Hashable {

    /** The name of the activity performed. */
    public private(set) var activity: String
    /** The day and time the activity was started, formatted according to ISO-8601. */
    public private(set) var startDate: Date
    /** The length of the workout, in minutes. */
    public private(set) var durationMinutes: Double
    /** The amount of calories the user burned. */
    public private(set) var caloriesBurned: Double

    public init(activity: String, startDate: Date, durationMinutes: Double, caloriesBurned: Double) {
        self.activity = activity
        self.startDate = startDate
        self.durationMinutes = durationMinutes
        self.caloriesBurned = caloriesBurned
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activity
        case startDate = "start_date"
        case durationMinutes = "duration_minutes"
        case caloriesBurned = "calories_burned"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(activity, forKey: .activity)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(durationMinutes, forKey: .durationMinutes)
        try container.encode(caloriesBurned, forKey: .caloriesBurned)
    }
}

