//
// PostAssistantResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A assistant POST response. */
public struct PostAssistantResponse: Codable, JSONEncodable, Hashable {

    /** A test field for an assistant response. */
    public private(set) var testOutput: String?

    public init(testOutput: String? = nil) {
        self.testOutput = testOutput
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case testOutput = "test_output"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(testOutput, forKey: .testOutput)
    }
}

