//
// PostSleepAssistantResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A sleep assistant POST response. */
public struct PostSleepAssistantResponse: Codable, JSONEncodable, Hashable {

    /** The IDs that the backend is using for communicating with assistants. This is a string blob that can be converted into JSON. This allows the client to not need to specifically decode the object, and just return it directly. Clients should echo these values back. */
    public private(set) var automatedIds: String
    /** A list of directives for the user. */
    public private(set) var directives: [UserDirective]

    public init(automatedIds: String, directives: [UserDirective]) {
        self.automatedIds = automatedIds
        self.directives = directives
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case automatedIds = "automated_ids"
        case directives
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(automatedIds, forKey: .automatedIds)
        try container.encode(directives, forKey: .directives)
    }
}

