//
// PostAssistantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A assistant POST request. */
public struct PostAssistantRequest: Codable, JSONEncodable, Hashable {

    /** A test field for an assistant request */
    public private(set) var testInput: String
    public private(set) var marksName: String?

    public init(testInput: String, marksName: String? = nil) {
        self.testInput = testInput
        self.marksName = marksName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case testInput = "test_input"
        case marksName = "marks_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(testInput, forKey: .testInput)
        try container.encodeIfPresent(marksName, forKey: .marksName)
    }
}

