//
// PostAssistantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An assistant POST request. */
public struct PostAssistantRequest: Codable, JSONEncodable, Hashable {

    /** A test field for an assistant request */
    public private(set) var testInput: String

    public init(testInput: String) {
        self.testInput = testInput
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case testInput = "test_input"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(testInput, forKey: .testInput)
    }
}

