//
// PostSleepAssistantResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A sleep assistant POST response. */
public struct PostSleepAssistantResponse: Codable, JSONEncodable, Hashable {

    /** The IDs that the backend is using for communicating with assistants. This is a string blob that can be converted into JSON. This allows the client to not need to specifically decode the object, and just return it directly. Clients should echo these values back. */
    public private(set) var automatedIds: String?
    /** A recommendation of what to do. */
    public private(set) var recommendation: String?

    public init(automatedIds: String? = nil, recommendation: String? = nil) {
        self.automatedIds = automatedIds
        self.recommendation = recommendation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case automatedIds = "automated_ids"
        case recommendation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(automatedIds, forKey: .automatedIds)
        try container.encodeIfPresent(recommendation, forKey: .recommendation)
    }
}

