//
// PostSleepAssistantRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A sleep assistant POST request. */
public struct PostSleepAssistantRequest: Codable, JSONEncodable, Hashable {

    /** The IDs that the backend is using for communicating with assistants. This is a string blob that can be converted into JSON. This allows the client to not need to specifically decode the object, and just return it directly. Clients should echo these values back. */
    public private(set) var automatedIds: String
    public private(set) var userInfo: UserInfo?
    public private(set) var sleepHealthSnapshot: SleepHealthSnapshot?

    public init(automatedIds: String, userInfo: UserInfo? = nil, sleepHealthSnapshot: SleepHealthSnapshot? = nil) {
        self.automatedIds = automatedIds
        self.userInfo = userInfo
        self.sleepHealthSnapshot = sleepHealthSnapshot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case automatedIds = "automated_ids"
        case userInfo
        case sleepHealthSnapshot
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(automatedIds, forKey: .automatedIds)
        try container.encodeIfPresent(userInfo, forKey: .userInfo)
        try container.encodeIfPresent(sleepHealthSnapshot, forKey: .sleepHealthSnapshot)
    }
}

