//
// SleepHealthSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A snapshot of the user&#39;s sleep health metrics. */
public struct SleepHealthSnapshot: Codable, JSONEncodable, Hashable {

    public private(set) var timeInDaylight: [HealthMetricSample]?
    public private(set) var restingHeartRate: [HealthMetricSample]?
    public private(set) var meditation: [HealthMetricSample]?
    public private(set) var workouts: [HealthWorkout]?
    public private(set) var sleepSummaries: [SleepSummary]?

    public init(timeInDaylight: [HealthMetricSample]? = nil, restingHeartRate: [HealthMetricSample]? = nil, meditation: [HealthMetricSample]? = nil, workouts: [HealthWorkout]? = nil, sleepSummaries: [SleepSummary]? = nil) {
        self.timeInDaylight = timeInDaylight
        self.restingHeartRate = restingHeartRate
        self.meditation = meditation
        self.workouts = workouts
        self.sleepSummaries = sleepSummaries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timeInDaylight = "time_in_daylight"
        case restingHeartRate = "resting_heart_rate"
        case meditation
        case workouts
        case sleepSummaries = "sleep_summaries"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timeInDaylight, forKey: .timeInDaylight)
        try container.encodeIfPresent(restingHeartRate, forKey: .restingHeartRate)
        try container.encodeIfPresent(meditation, forKey: .meditation)
        try container.encodeIfPresent(workouts, forKey: .workouts)
        try container.encodeIfPresent(sleepSummaries, forKey: .sleepSummaries)
    }
}

