//
// SleepSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A summary of a single night&#39;s sleep for the user. */
public struct SleepSummary: Codable, JSONEncodable, Hashable {

    /** The start date of the sleep session, formatted using ISO-8601. */
    public private(set) var startDate: Date?
    /** The end date of the sleep session, formatted using ISO-8601. */
    public private(set) var endDate: Date?
    /** The number of minutes the user spent in deep sleep. */
    public private(set) var deepSleepMinutes: Double?
    /** The number of minutes the user spent in core sleep. */
    public private(set) var coreSleepMinutes: Double?
    /** The number of minutes the user spent in REM sleep. */
    public private(set) var remSleepMinutes: Double?
    /** The number of minutes the user spent awake. */
    public private(set) var awakeSleepMinutes: Double?

    public init(startDate: Date? = nil, endDate: Date? = nil, deepSleepMinutes: Double? = nil, coreSleepMinutes: Double? = nil, remSleepMinutes: Double? = nil, awakeSleepMinutes: Double? = nil) {
        self.startDate = startDate
        self.endDate = endDate
        self.deepSleepMinutes = deepSleepMinutes
        self.coreSleepMinutes = coreSleepMinutes
        self.remSleepMinutes = remSleepMinutes
        self.awakeSleepMinutes = awakeSleepMinutes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startDate = "start_date"
        case endDate = "end_date"
        case deepSleepMinutes = "deep_sleep_minutes"
        case coreSleepMinutes = "core_sleep_minutes"
        case remSleepMinutes = "rem_sleep_minutes"
        case awakeSleepMinutes = "awake_sleep_minutes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startDate, forKey: .startDate)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(deepSleepMinutes, forKey: .deepSleepMinutes)
        try container.encodeIfPresent(coreSleepMinutes, forKey: .coreSleepMinutes)
        try container.encodeIfPresent(remSleepMinutes, forKey: .remSleepMinutes)
        try container.encodeIfPresent(awakeSleepMinutes, forKey: .awakeSleepMinutes)
    }
}

