//
// TimeComponent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An object to represent an hour:minute pair during a day. */
public struct TimeComponent: Codable, JSONEncodable, Hashable {

    /** The hour in 24 hour time. */
    public private(set) var hour: Int
    /** The minute of the time component. */
    public private(set) var minute: Int

    public init(hour: Int, minute: Int) {
        self.hour = hour
        self.minute = minute
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hour
        case minute
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hour, forKey: .hour)
        try container.encode(minute, forKey: .minute)
    }
}

