//
// UserDirectiveSupplementDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A directive from the AI on what supplement the user should take to improve their health. */
public struct UserDirectiveSupplementDetails: Codable, JSONEncodable, Hashable {

    /** The amount of the supplement to take. */
    public private(set) var dosageAmount: Double
    /** The unit of the supplement dosage. */
    public private(set) var dosageUnit: String
    public private(set) var scheduleTimeComponent: TimeComponent
    /** Whether Bloom should remind the user at the scheduled time with a notification. */
    public private(set) var alertsUser: Bool

    public init(dosageAmount: Double, dosageUnit: String, scheduleTimeComponent: TimeComponent, alertsUser: Bool) {
        self.dosageAmount = dosageAmount
        self.dosageUnit = dosageUnit
        self.scheduleTimeComponent = scheduleTimeComponent
        self.alertsUser = alertsUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dosageAmount = "dosage_amount"
        case dosageUnit = "dosage_unit"
        case scheduleTimeComponent = "schedule_time_component"
        case alertsUser = "alerts_user"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dosageAmount, forKey: .dosageAmount)
        try container.encode(dosageUnit, forKey: .dosageUnit)
        try container.encode(scheduleTimeComponent, forKey: .scheduleTimeComponent)
        try container.encode(alertsUser, forKey: .alertsUser)
    }
}

