//
// UserDirective.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A directive from the AI on what the user should do to improve their health. */
public struct UserDirective: Codable, JSONEncodable, Hashable {

    /** The title for the directive. For example, \"Take Melatonin each night\". */
    public private(set) var title: String
    /** A description of how the directive will help with the user's goals. */
    public private(set) var description: String
    /** An SFSymbol that can be used by the app that represents the directive. */
    public private(set) var sfSymbol: String
    public private(set) var supplementDetails: UserDirectiveSupplementDetails?
    public private(set) var activityDetails: UserDirectiveActivityDetails?
    public private(set) var screenTimeAdjustment: UserDirectiveScreenTimeScheduleAdjustment?

    public init(title: String, description: String, sfSymbol: String, supplementDetails: UserDirectiveSupplementDetails? = nil, activityDetails: UserDirectiveActivityDetails? = nil, screenTimeAdjustment: UserDirectiveScreenTimeScheduleAdjustment? = nil) {
        self.title = title
        self.description = description
        self.sfSymbol = sfSymbol
        self.supplementDetails = supplementDetails
        self.activityDetails = activityDetails
        self.screenTimeAdjustment = screenTimeAdjustment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case description
        case sfSymbol = "sf_symbol"
        case supplementDetails = "supplement_details"
        case activityDetails = "activity_details"
        case screenTimeAdjustment = "screen_time_adjustment"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(description, forKey: .description)
        try container.encode(sfSymbol, forKey: .sfSymbol)
        try container.encodeIfPresent(supplementDetails, forKey: .supplementDetails)
        try container.encodeIfPresent(activityDetails, forKey: .activityDetails)
        try container.encodeIfPresent(screenTimeAdjustment, forKey: .screenTimeAdjustment)
    }
}

