//
// UserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** General information about the user. */
public struct UserInfo: Codable, JSONEncodable, Hashable {

    /** The user's name. */
    public private(set) var name: String?
    /** The user's age in years. */
    public private(set) var age: Int?
    /** The user's sex. */
    public private(set) var sex: String?
    public private(set) var location: Location?

    public init(name: String? = nil, age: Int? = nil, sex: String? = nil, location: Location? = nil) {
        self.name = name
        self.age = age
        self.sex = sex
        self.location = location
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case age
        case sex
        case location
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(age, forKey: .age)
        try container.encodeIfPresent(sex, forKey: .sex)
        try container.encodeIfPresent(location, forKey: .location)
    }
}

