//
// UserDirectiveActivityDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A directive from the AI on what actvity the user should perform to improve their health. */
public struct UserDirectiveActivityDetails: Codable, JSONEncodable, Hashable {

    /** The recommended length of the activity in minutes. */
    public private(set) var recommendedDurationMinutes: Int
    public private(set) var proposedTimeComponent: TimeComponent?

    public init(recommendedDurationMinutes: Int, proposedTimeComponent: TimeComponent? = nil) {
        self.recommendedDurationMinutes = recommendedDurationMinutes
        self.proposedTimeComponent = proposedTimeComponent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recommendedDurationMinutes = "recommended_duration_minutes"
        case proposedTimeComponent = "proposed_time_component"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recommendedDurationMinutes, forKey: .recommendedDurationMinutes)
        try container.encodeIfPresent(proposedTimeComponent, forKey: .proposedTimeComponent)
    }
}

