//
// UserDirectiveScreenTimeScheduleAdjustment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A directive from the AI to update the Screen Time content restriction schedule. */
public struct UserDirectiveScreenTimeScheduleAdjustment: Codable, JSONEncodable, Hashable {

    public private(set) var proposedStartTime: TimeComponent
    public private(set) var poposedEndTime: TimeComponent

    public init(proposedStartTime: TimeComponent, poposedEndTime: TimeComponent) {
        self.proposedStartTime = proposedStartTime
        self.poposedEndTime = poposedEndTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case proposedStartTime = "proposed_start_time"
        case poposedEndTime = "poposed_end_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(proposedStartTime, forKey: .proposedStartTime)
        try container.encode(poposedEndTime, forKey: .poposedEndTime)
    }
}

