//
//  FoodItem+Preview.swift
//  Supplements
//
//  Created by Mark DiFranco on 2024-11-26.
//

import BloomModel

extension FoodItem {
  enum Preview { }
}

extension FoodItem.Preview {
  static let ritzCrackers = FoodItem(
    id: FoodItemIdentifier("1234"),
    name: "Crackers",
    brandName: "Ritz",
    flavour: "Low Sodium",
    country: .canada,
    calories: FoodItem.Quantity(value: 100, unit: "kcal"),
    protein: FoodItem.Quantity(value: 1, unit: "g"),
    carbohydrates: FoodItem.Quantity(value: 13, unit: "g"),
    fat: FoodItem.Quantity(value: 4.5, unit: "g"),
    saturatedFat: FoodItem.Quantity(value: 3, unit: "g"),
    transFat: FoodItem.Quantity(value: 1.5, unit: "g"),
    polyunsaturatedFat: nil,
    monounsaturatedFat: nil,
    fiber: FoodItem.Quantity(value: 4, unit: "g"),
    sugar: FoodItem.Quantity(value: 1, unit: "g"),
    cholesterol: nil,
    sodium: FoodItem.Quantity(value: 130, unit: "mg"),
    calcium: nil,
    iron: nil,
    potassium: FoodItem.Quantity(value: 80, unit: "mg"),
    magnesium: nil,
    zinc: nil,
    vitaminA: FoodItem.Quantity(value: 0.358, unit: "mg"),
    vitaminB6: nil,
    vitaminB12: nil,
    vitaminC: nil,
    vitaminD: FoodItem.Quantity(value: 120, unit: "mcg"),
    vitaminE: nil,
    servingName: "6 crackers",
    servingQuantity: FoodItem.Quantity(value: 20, unit: "g"),
    ingredients: "Yogurt (Milk);  Rhubarb (8%);  Sugar;  Tapioca Starch;  Natural Flavourings;  Colour (Plain Caramel);  Stabiliser (Pectin);  Milk Minerals;  Cultures (Lactobacillus Bulgaricus;  Streptococcus Thermophilus;  Lactococcus Lactis;  Bifidobacterium Lactis (Bifidus Actiregularis®))",
    category: .branded,
    isVerified: true
  )

  static let unverifiedRitzCrackers = FoodItem(
    id: FoodItemIdentifier("1234"),
    name: "Crackers",
    brandName: "Ritz",
    flavour: "Low Sodium",
    country: .canada,
    calories: FoodItem.Quantity(value: 100, unit: "kcal"),
    protein: FoodItem.Quantity(value: 1, unit: "g"),
    carbohydrates: FoodItem.Quantity(value: 13, unit: "g"),
    fat: FoodItem.Quantity(value: 4.5, unit: "g"),
    saturatedFat: nil,
    transFat: nil,
    polyunsaturatedFat: nil,
    monounsaturatedFat: nil,
    fiber: nil,
    sugar: nil,
    cholesterol: nil,
    sodium: nil,
    calcium: nil,
    iron: nil,
    potassium: nil,
    magnesium: nil,
    zinc: nil,
    vitaminA: nil,
    vitaminB6: nil,
    vitaminB12: nil,
    vitaminC: nil,
    vitaminD: nil,
    vitaminE: nil,
    servingName: "6 crackers",
    servingQuantity: FoodItem.Quantity(value: 20, unit: "g"),
    ingredients: "Yogurt (Milk);  Rhubarb (8%);  Sugar;  Tapioca Starch;  Natural Flavourings;  Colour (Plain Caramel);  Stabiliser (Pectin);  Milk Minerals;  Cultures (Lactobacillus Bulgaricus;  Streptococcus Thermophilus;  Lactococcus Lactis;  Bifidobacterium Lactis (Bifidus Actiregularis®))",
    category: .branded,
    isVerified: false
  )

  static let grilledSalmon = FoodItem(
    id: FoodItemIdentifier("1234"),
    name: "Grilled Salmon",
    brandName: "Fish",
    flavour: nil,
    country: .canada,
    calories: FoodItem.Quantity(value: 280, unit: "kcal"),
    protein: nil,
    carbohydrates: nil,
    fat: nil,
    saturatedFat: nil,
    transFat: nil,
    polyunsaturatedFat: nil,
    monounsaturatedFat: nil,
    fiber: nil,
    sugar: nil,
    cholesterol: nil,
    sodium: nil,
    calcium: nil,
    iron: nil,
    potassium: nil,
    magnesium: nil,
    zinc: nil,
    vitaminA: nil,
    vitaminB6: nil,
    vitaminB12: nil,
    vitaminC: nil,
    vitaminD: nil,
    vitaminE: nil,
    servingName: "1 Fillet",
    servingQuantity: FoodItem.Quantity(value: 150, unit: "g"),
    ingredients: nil,
    category: .generic,
    isVerified: false
  )

  static let mixedLettuce = FoodItem(
    id: FoodItemIdentifier("5678"),
    name: "Mixed Lettuce",
    brandName: "Salad",
    flavour: nil,
    country: .canada,
    calories: FoodItem.Quantity(value: 30, unit: "kcal"),
    protein: nil,
    carbohydrates: nil,
    fat: nil,
    saturatedFat: nil,
    transFat: nil,
    polyunsaturatedFat: nil,
    monounsaturatedFat: nil,
    fiber: nil,
    sugar: nil,
    cholesterol: nil,
    sodium: nil,
    calcium: nil,
    iron: nil,
    potassium: nil,
    magnesium: nil,
    zinc: nil,
    vitaminA: nil,
    vitaminB6: nil,
    vitaminB12: nil,
    vitaminC: nil,
    vitaminD: nil,
    vitaminE: nil,
    servingName: "1 Bowl",
    servingQuantity: FoodItem.Quantity(value: 100, unit: "g"),
    ingredients: nil,
    category: .generic,
    isVerified: false
  )

  static let slicedCarrots = FoodItem(
    id: FoodItemIdentifier("9012"),
    name: "Sliced Carrots",
    brandName: "Vegetables",
    flavour: nil,
    country: .canada,
    calories: FoodItem.Quantity(value: 10, unit: "kcal"),
    protein: nil,
    carbohydrates: nil,
    fat: nil,
    saturatedFat: nil,
    transFat: nil,
    polyunsaturatedFat: nil,
    monounsaturatedFat: nil,
    fiber: nil,
    sugar: nil,
    cholesterol: nil,
    sodium: nil,
    calcium: nil,
    iron: nil,
    potassium: nil,
    magnesium: nil,
    zinc: nil,
    vitaminA: nil,
    vitaminB6: nil,
    vitaminB12: nil,
    vitaminC: nil,
    vitaminD: nil,
    vitaminE: nil,
    servingName: "1 Carrot",
    servingQuantity: FoodItem.Quantity(value: 15, unit: "g"),
    ingredients: nil,
    category: .generic,
    isVerified: false
  )

  static let cherryTomatoes = FoodItem(
    id: FoodItemIdentifier("3456"),
    name: "Cherry Tomatoes",
    brandName: "Vegetables",
    flavour: nil,
    country: .canada,
    calories: FoodItem.Quantity(value: 40, unit: "kcal"),
    protein: nil,
    carbohydrates: nil,
    fat: nil,
    saturatedFat: nil,
    transFat: nil,
    polyunsaturatedFat: nil,
    monounsaturatedFat: nil,
    fiber: nil,
    sugar: nil,
    cholesterol: nil,
    sodium: nil,
    calcium: nil,
    iron: nil,
    potassium: nil,
    magnesium: nil,
    zinc: nil,
    vitaminA: nil,
    vitaminB6: nil,
    vitaminB12: nil,
    vitaminC: nil,
    vitaminD: nil,
    vitaminE: nil,
    servingName: "3 Tomatoes",
    servingQuantity: FoodItem.Quantity(value: 45, unit: "g"),
    ingredients: nil,
    category: .generic,
    isVerified: false
  )
}
