//
// AssistantAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AssistantAPI {

    /**
     Request to perform assistant actions
     
     - parameter postAssistantRequest: (body) Assistant data 
     - returns: PostAssistantResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postAssistantRequest(postAssistantRequest: PostAssistantRequest) async throws -> PostAssistantResponse {
        return try await postAssistantRequestWithRequestBuilder(postAssistantRequest: postAssistantRequest).execute().body
    }

    /**
     Request to perform assistant actions
     - POST /assistant
     - parameter postAssistantRequest: (body) Assistant data 
     - returns: RequestBuilder<PostAssistantResponse> 
     */
    open class func postAssistantRequestWithRequestBuilder(postAssistantRequest: PostAssistantRequest) -> RequestBuilder<PostAssistantResponse> {
        let localVariablePath = "/assistant"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postAssistantRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PostAssistantResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Request to sleep assistant
     
     - parameter postSleepAssistantRequest: (body) Sleep assistant data request 
     - returns: PostSleepAssistantResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postSleepAssistant(postSleepAssistantRequest: PostSleepAssistantRequest) async throws -> PostSleepAssistantResponse {
        return try await postSleepAssistantWithRequestBuilder(postSleepAssistantRequest: postSleepAssistantRequest).execute().body
    }

    /**
     Request to sleep assistant
     - POST /assistant/sleep
     - parameter postSleepAssistantRequest: (body) Sleep assistant data request 
     - returns: RequestBuilder<PostSleepAssistantResponse> 
     */
    open class func postSleepAssistantWithRequestBuilder(postSleepAssistantRequest: PostSleepAssistantRequest) -> RequestBuilder<PostSleepAssistantResponse> {
        let localVariablePath = "/assistant/sleep"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postSleepAssistantRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PostSleepAssistantResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
